apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-redis-chart.fullname" . }}-api
spec:
  type: ClusterIP
  selector:
    app: {{ include "api-redis-chart.name" . }}-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
