apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-redis-chart.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ include "api-redis-chart.name" . }}-redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
